SELECT DISTINCT EM1.NAME, EM2.POSITION FROM EMPLOYEE EM1, EMPLOYEE EM2 WHERE EM1.DEPARTMENT_ID = CURRENT_DEPARTMENT_ID AND EM2.DEPARTMENT_ID = CURRENT_DEPARTMENT_ID;

SELECT NAME FROM EMPLOYEE EMP1 WHERE EMP1.SALARY = 2 * (SELECT AVG(SALARY) FROM EMPLOYEE EMP2 WHERE EMP2.CHIEF_ID = EMP1.ID);
